"""Segment spot-like particles."""

import json
from pathlib import Path
from typing import Optional

# import fractal_tasks_core
import numpy as np
from ngio import open_omezarr_container
from pydantic import validate_call
from skimage.segmentation import expand_labels

# __OME_NGFF_VERSION__ = fractal_tasks_core.__OME_NGFF_VERSION__


@validate_call
def expand_segmentation(
    *,
    # Fractal parameters
    zarr_url: str,
    # Core parameters
    input_ROI_table: str = "FOV_ROI_table",
    input_label_name: str = "nuclei",
    expansion_distance: int = 0,
    save_union: bool = True,
    output_label_name_union: Optional[str] = "cells",
    save_diff: bool = True,
    output_label_name_diff: Optional[str] = "cytoplasms",
    overwrite: bool = True,
) -> None:
    """Expand the labels on the ROIs of a single OME-Zarr image.

    Args:
        zarr_url: Path or url to the individual OME-Zarr image to be processed.
            (standard argument for Fractal tasks, managed by Fractal server).
        input_ROI_table: Name of `organoid_ROI_table` => loop over the organoid
            ROI table (generated by another task), `well_ROI_table` => process
            the whole well  the ROI table over which the task loops to
            expand labels. Examples: `FOV_ROI_table` => loop over
            the field of views,as one image.
        input_label_name: Name of the input label image to be expanded (e.g.
            `"nuclei"`).
        expansion_distance: Distance by which the labels are expanded, in
            pixels at level 0.
        save_union: If `True`, save the union of the original and expanded
            labels. (corresponds to e.g. the intire cell)
        output_label_name_union: Name of the output label image for the union
            (e.g. `"cells"`).
        save_diff: If `True`, save the difference between the original and
            expanded labels. (corresponds to e.g. the cytoplasm)
        output_label_name_diff: Name of the output label image for the
            difference (e.g. `"cytoplasms"`).
        overwrite: If `True`, overwrite the task output.
    """
    omezarr = open_omezarr_container(zarr_url)
    input_label_image = omezarr.get_label(name=input_label_name)

    roi_table = omezarr.get_table(input_ROI_table, check_type="roi_table")

    if save_union:
        output_label_image_union = omezarr.derive_label(
            name=output_label_name_union,
            overwrite=overwrite,
            dtype=input_label_image.dtype,
        )
    if save_diff:
        output_label_image_diff = omezarr.derive_label(
            name=output_label_name_diff,
            overwrite=overwrite,
            dtype=input_label_image.dtype,
        )

    for roi in roi_table.rois():
        patch = input_label_image.get_roi(roi)
        segmentation = expand_labels_ROI(patch, expansion_distance=expansion_distance)
        if save_union:
            output_label_image_union.set_roi(patch=segmentation, roi=roi)
        if save_diff:
            output_label_image_diff.set_roi(patch=segmentation - patch, roi=roi)

    # Consolidate the segmentation image
    if save_union:
        output_label_image_union.consolidate()
    if save_diff:
        output_label_image_diff.consolidate()

    # TODO: Add ROI table with bounding boxes of the labels

    # TODO: fix label .zattrs (wait for ngio update)
    # QUICK FIX: Manually adjust the label image .zattrs
    if save_union:
        with open(
            Path(zarr_url) / "labels" / output_label_name_union / ".zattrs", "r+"
        ) as f:
            json_data = json.load(f)
            json_data["image-label"] = json_data.pop("image_label")
            json_data["multiscales"][0]["name"] = output_label_name_union
            f.seek(0)
            json.dump(json_data, f, indent=4)
            f.truncate()
    if save_diff:
        with open(
            Path(zarr_url) / "labels" / output_label_name_diff / ".zattrs", "r+"
        ) as f:
            json_data = json.load(f)
            json_data["image-label"] = json_data.pop("image_label")
            json_data["multiscales"][0]["name"] = output_label_name_diff
            f.seek(0)
            json.dump(json_data, f, indent=4)
            f.truncate()


def expand_labels_ROI(
    x: np.ndarray,
    expansion_distance: int = 0,
) -> np.ndarray:
    """Expand labels for a single ROI.

    Args:
        x: 3D numpy array of labels
        expansion_distance: Distance by which the labels are expanded, in
            pixels.
    """
    if x.ndim != 3 and x.shape[0] != 1:
        raise ValueError("Input array must be 3D with the first dimension being 1.")
    return expand_labels(x[0], expansion_distance).reshape(x.shape)


# if __name__ == "__main__":
#     from fractal_tasks_core.tasks._utils import run_fractal_task

#     run_fractal_task(task_function=segment_particles)
